print("a")
print ("Twinkle, twinkle, little star,")
print ("\t", "How I wonder what you are!")
print ("\t\t", "Up above the world so high")
print ("\t\t", "Like a diamond in the sky.")
print ("Twinkle, twinkle, little star,")
print ("\t", "How I wonder what you are!")

print("b")
print("Hello Python world!")
print("\tHello\tPython\tworld!")
print("Hello\nPython\nworld!")
print("Hello","Python","world!\n", end="")
print("Hello","Python","world!", sep=" ")

print("c")
print ("\t\tname: Lilit \t\t surname: Harutyunyan")
print ("")
print ("\t\toffice: RioGrande \t field: software&sales")
print ("")
print ("\tProfessional Experience:")
print ("2021-Present \tRaffael Contini Trading Company Joint Venture LLC")
print ("\t\tAS SM specialist , Operations Team Lead")
print ("2019-2021\tEffect Group CJSC")
print ("\t\tAS SM specialist, Senior Specialist in Sales Department")
print ("2018-2019\tArmenian Software LLC (ArmSoft)", sep="\t")
print ("\t\tEngineer-economist (AS Sales Management(SM)) software")
print ("2015-2017\tTumo Center for Creative Technologies")
print ("\t\tAssistant Manager")
print ("")
print ("\tEducation:\n\t\tYerevan State University of Architecture and Construction")
print ("\t\tFaculty of economics and construction technologies")
print ("\t\tMaster’s in Enterprise Economics and Technologies")
print ("")
print ("\tITskills:\n\t\tMicrosoft Office (Word,Excel,PowerPoint),\n\t\tSales Management,Armsoft-Enterprises,AS-Accounting,E-Invoicing,\n\t\tHelp & Manual,etc.")
print ("")
print ("\t\tHobbies: Swimming")
print ("\t\tHobbies: Swimming")



